//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinger.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DarkOrange {
            get {
                object obj = ResourceManager.GetObject("DarkOrange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на # Английский язык для программы Pinger
        ///#
        ///# Версия 1.0 от 21.02.2016;
        ///
        ///CultureInfo						= &quot;en-US&quot;;
        ///
        ///TXT_FORM_SERVER					= &quot;Server&quot;;
        ///TXT_FORM_LOG_MESSAGE			= &quot;Response from %s1: Time=%s2 мс, TTL=%s3&quot;
        ///TXT_FORM_LABEL_CLICK			= &quot;Thanks for the mail&quot;;
        ///TXT_FORM_LOG_MESSAGE_ERROR		= &quot;Request interrupted due to timeout&quot;;
        ///
        ///TXT_TRAY_START_MESSAGE			= &quot;Update information...&quot;;
        ///TXT_TRAY_MESSAGE				= &quot;Server: %s1 \nDelay %s2 мс \n\nYes force be with you ;-)&quot;
        ///
        ///TXT_CONTEXT_SHOW				= &quot;Show&quot;;
        ///TXT_CONTEXT_LANGUA [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Eng {
            get {
                return ResourceManager.GetString("Eng", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon greenOk {
            get {
                object obj = ResourceManager.GetObject("greenOk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Orange {
            get {
                object obj = ResourceManager.GetObject("Orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Red {
            get {
                object obj = ResourceManager.GetObject("Red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon redMinus {
            get {
                object obj = ResourceManager.GetObject("redMinus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на # Русский язык для программы Pinger
        ///#
        ///# Версия 1.0 от 21.02.2016;
        ///
        ///CultureInfo						= &quot;ru-RU&quot;;
        ///
        ///TXT_FORM_SERVER					= &quot;Сервер&quot;;
        ///TXT_FORM_LOG_MESSAGE			= &quot;Ответ от %s1: Время=%s2 мс, TTL=%s3&quot;
        ///TXT_FORM_LABEL_CLICK			= &quot;Пасибки за переход :-)&quot;;
        ///TXT_FORM_LOG_MESSAGE_ERROR		= &quot;Запрос прерван из за таймаута&quot;;
        ///
        ///TXT_TRAY_START_MESSAGE			= &quot;Обновление информации...&quot;;
        ///TXT_TRAY_MESSAGE				= &quot;Сервер: %s1 \nЗадержка %s2 мс \n\nДа прибудет с вами сила ;-)&quot;
        ///
        ///TXT_CONTEXT_SHOW				= &quot;Показать&quot;;
        ///TXT_CONTEXT_LAN [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ru {
            get {
                return ResourceManager.GetString("Ru", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_edit1 {
            get {
                object obj = ResourceManager.GetObject("save_edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Transfer {
            get {
                object obj = ResourceManager.GetObject("Transfer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Yellow {
            get {
                object obj = ResourceManager.GetObject("Yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
